/** Maps skill node id → internal RPG icon key */
export type SkillIconKey =
  | 'brush'
  | 'grid'
  | 'cube'
  | 'frame'
  | 'pencil'
  | 'bolt'
  | 'wave'
  | 'contrast'
  | 'laurel'
  | 'tablet'
  | 'palette'
  | 'gesture'
  | 'nib'
  | 'blueprint'
  | 'layers'
  | 'weave'
  | 'speed'
  | 'scroll'
  | 'bone'
  | 'skull'
  | 'muscle'
  | 'ruler'
  | 'figure'
  | 'hand'
  | 'foot'
  | 'head'
  | 'lens'
  | 'motion'
  | 'foreshort'
  | 'face'
  | 'eye'
  | 'hair'
  | 'robe'
  | 'shirt'
  | 'clapper'
  | 'clock'
  | 'spacing'
  | 'arc'
  | 'walk'
  | 'run'
  | 'idle'
  | 'blend'
  | 'smile'
  | 'drama'
  | 'squash'
  | 'anticipate'
  | 'puppet'
  | 'follow'
  | 'solid'
  | 'stage'
  | 'spark'
  | 'particles'
  | 'energy'
  | 'rain'
  | 'impact'
  | 'orb'
  | 'flame'
  | 'star'
  | 'smoke'
  | 'water'
  | 'lens_fx'
  | 'book'
  | 'scene'
  | 'chart'
  | 'heart'
  | 'panels'
  | 'books'
  | 'arc_story'
  | 'target'
  | 'globe'
  | 'magnifier'
  | 'camera'
  | 'storyboard'
  | 'filmstrip'
  | 'chain'
  | 'mask'
  | 'silhouette'
  | 'triangle'
  | 'thought'
  | 'crowd'
  | 'costume'
  | 'turn'
  | 'sheet'
  | 'dragon'
  | 'cog'
  | 'landscape'
  | 'mountain'
  | 'temple'
  | 'tree'
  | 'home'
  | 'props'
  | 'lamp'
  | 'city'
  | 'matte'
  | 'default'

export const NODE_SKILL_ICON_KEYS: Record<string, SkillIconKey> = {
  drawing_fundamentals: 'brush',
  drawing_perspective: 'grid',
  drawing_shapes: 'cube',
  drawing_composition: 'frame',
  drawing_practice: 'pencil',
  drawing_quick_sketch: 'bolt',
  drawing_contour: 'wave',
  drawing_value: 'contrast',
  drawing_advanced: 'laurel',
  drawing_digital: 'tablet',
  drawing_color: 'palette',
  drawing_gesture: 'gesture',
  drawing_line_quality: 'nib',
  drawing_construction: 'blueprint',
  drawing_simplification: 'layers',
  drawing_texture: 'weave',
  drawing_rendering: 'brush',
  drawing_speedpaint: 'speed',
  drawing_studies: 'scroll',

  anatomy_fundamentals: 'bone',
  anatomy_skeleton: 'skull',
  anatomy_muscles: 'muscle',
  anatomy_proportions: 'ruler',
  anatomy_body: 'figure',
  anatomy_hands: 'hand',
  anatomy_feet: 'foot',
  anatomy_head: 'head',
  anatomy_advanced: 'lens',
  anatomy_dynamics: 'motion',
  anatomy_foreshortening: 'foreshort',
  anatomy_facial_features: 'face',
  anatomy_eyes: 'eye',
  anatomy_hair: 'hair',
  anatomy_drapery: 'robe',
  anatomy_clothing: 'shirt',

  animation_fundamentals: 'clapper',
  animation_timing: 'clock',
  animation_spacing: 'spacing',
  animation_arcs: 'arc',
  animation_walk: 'walk',
  animation_run: 'run',
  animation_idle: 'idle',
  animation_transitions: 'blend',
  animation_expressions: 'smile',
  animation_complex: 'drama',
  animation_squash_stretch: 'squash',
  animation_anticipation: 'anticipate',
  animation_secondary: 'puppet',
  animation_follow_through: 'follow',
  animation_solid_drawing: 'solid',
  animation_staging: 'stage',

  effects_fundamentals: 'spark',
  effects_particles: 'particles',
  effects_energy: 'energy',
  effects_weather: 'rain',
  effects_combat: 'impact',
  effects_magic: 'orb',
  effects_elements: 'flame',
  effects_advanced: 'star',
  effects_particle_advanced: 'particles',
  effects_post_process: 'lens_fx',
  effects_smoke: 'smoke',
  effects_fire: 'flame',
  effects_water: 'water',

  storytelling_fundamentals: 'book',
  storytelling_visual: 'scene',
  storytelling_pacing: 'chart',
  storytelling_emotion: 'heart',
  storytelling_panels: 'panels',
  storytelling_sequential: 'books',
  storytelling_character_arc: 'arc_story',
  storytelling_advanced: 'target',
  storytelling_world: 'globe',
  storytelling_thematic: 'magnifier',
  storytelling_camera: 'camera',
  storytelling_shots: 'camera',
  storytelling_visual_dev: 'palette',
  storytelling_storyboard: 'storyboard',
  storytelling_animatics: 'filmstrip',
  storytelling_continuity: 'chain',

  character_design_fundamentals: 'mask',
  character_silhouette: 'silhouette',
  character_shape_language: 'triangle',
  character_proportions: 'ruler',
  character_personality: 'thought',
  character_variety: 'crowd',
  character_costume: 'costume',
  character_expressions: 'smile',
  character_turnaround: 'turn',
  character_sheet: 'sheet',
  character_creatures: 'dragon',
  character_mechanical: 'cog',

  environment_fundamentals: 'landscape',
  environment_perspective: 'mountain',
  environment_composition: 'frame',
  environment_architecture: 'temple',
  environment_nature: 'tree',
  environment_interior: 'home',
  environment_props: 'props',
  environment_lighting: 'lamp',
  environment_mood: 'city',
  environment_matte: 'matte',
}

export const CATEGORY_FALLBACK_ICON: Record<string, SkillIconKey> = {
  drawing: 'brush',
  anatomy: 'bone',
  animation: 'clapper',
  effects: 'spark',
  storytelling: 'book',
  character_design: 'mask',
  environment: 'landscape',
}
