/**
 * Polishes autogenerated YouTube quest titles to be more human-readable.
 *
 * Usage: npx tsx scripts/polish-youtube-quest-titles.ts
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const DATA_DIR = path.join(__dirname, '../src/renderer/data')

const FILES = [
  'quests_drawing.json',
  'quests_anatomy.json',
  'quests_animation.json',
  'quests_effects.json',
  'quests_storytelling.json',
  'quests_character_design.json',
  'quests_environment.json',
]

type Quest = {
  id: number
  title: { en?: string; ru?: string }
}

function isYoutubePackId(id: number): boolean {
  return id >= 11001 && id <= 14000
}

function polishEn(s: string): string {
  let t = s.trim()
  t = t.replace(/\s+/g, ' ')
  t = t.replace(/\s*:\s*/g, ' — ')
  t = t.replace(/\bMileage page\b/gi, 'Mileage')
  t = t.replace(/\bset\b/gi, 'Set')
  t = t.replace(/\(\s*(\d+)\s*frames\s*\)/gi, '($1 frames)')
  t = t.replace(/\(\s*(\d+)\s*\)/g, '($1)')
  // Avoid double spaces around dash
  t = t.replace(/\s+—\s+/g, ' — ')
  return t
}

function polishRu(s: string): string {
  let t = s.trim()
  t = t.replace(/\s+/g, ' ')
  t = t.replace(/\s*:\s*/g, ' — ')
  t = t.replace(/\bMileage\b/gi, 'Практика')
  t = t.replace(/\s+—\s+/g, ' — ')
  return t
}

async function main(): Promise<void> {
  let changed = 0
  for (const file of FILES) {
    const filePath = path.join(DATA_DIR, file)
    const raw = JSON.parse(await fs.readFile(filePath, 'utf8')) as Quest[]
    let fileChanged = 0

    for (const q of raw) {
      if (!isYoutubePackId(q.id)) continue
      if (q.title?.en) {
        const next = polishEn(q.title.en)
        if (next !== q.title.en) {
          q.title.en = next
          fileChanged++
        }
      }
      if (q.title?.ru) {
        const next = polishRu(q.title.ru)
        if (next !== q.title.ru) {
          q.title.ru = next
          fileChanged++
        }
      }
    }

    if (fileChanged > 0) {
      await fs.writeFile(filePath, JSON.stringify(raw, null, 2) + '\n', 'utf8')
      changed += fileChanged
      console.log(`${file}: updated ${fileChanged} titles`)
    }
  }
  console.log(`Total title updates: ${changed}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})

