/** Pack A — Fundamentals drills (drawing + anatomy). inspiredBy = YouTube channel key */
import { mc, type QuestDraft } from './youtube-quest-helpers.ts'

export const PACK_A: QuestDraft[] = [
  {
    id: 11001,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'prokotv',
    source: 'Proko (YouTube)',
    title: { en: '16-Line Gesture: 8 Figures', ru: 'Жест методом 16 линий: 8 фигур' },
    description: {
      en: 'Draw 8 figure gestures using only 16 lines each (Hampton/Proko method). No erasing; 90 sec per pose.',
      ru: '8 жестовых фигур — не более 16 линий на каждую (метод Hampton/Proko). Без ластика; 90 сек на позу.',
    },
    xp: 48,
    estimatedTime: 18,
    min_level: 1,
    tags: ['gesture', 'rhythm', 'figure', 'practice'],
    medium: 'traditional',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      '16line-gesture',
      { en: '2 warmup scribbles — loose shoulder swings', ru: '2 разминочных жеста — свободные линии' },
      { en: '6 timed gestures, max 16 lines each', ru: '6 жестов по таймеру, макс. 16 линий' },
      { en: 'Pick best 2; add one line of action accent', ru: 'Выбери 2 лучших; усиль линию действия' },
      [3, 10, 5],
    ),
  },
  {
    id: 11002,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'drawlikeasir',
    source: 'Draw Like a Sir (YouTube)',
    title: { en: '3 Objects: Cubes Only', ru: '3 предмета: только кубы' },
    description: {
      en: 'Pick 3 everyday objects. Block each using only boxes — no curves or details.',
      ru: '3 бытовых предмета. Построй каждый только кубами — без кривых и деталей.',
    },
    xp: 42,
    estimatedTime: 15,
    min_level: 1,
    tags: ['construction', 'shapes', 'simplify'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'cubes-only',
      { en: 'Sketch 3 loose box thumbnails', ru: '3 эскиза-куба на выбор предмета' },
      { en: 'Draw all 3 objects as clean box stacks', ru: '3 предмета чистыми кубическими блоками' },
      { en: 'Label which face faces the light', ru: 'Отметь грани, обращённые к свету' },
      [4, 8, 3],
    ),
  },
  {
    id: 11003,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'drawlikeasir',
    source: 'Draw Like a Sir (YouTube)',
    title: { en: '3 Objects: Cylinders Only', ru: '3 предмета: только цилиндры' },
    description: {
      en: 'Same 3 objects (or new ones). Rebuild using cylinders and ellipses only.',
      ru: 'Те же 3 предмета (или новые). Перестрой только цилиндрами и эллипсами.',
    },
    xp: 44,
    estimatedTime: 15,
    min_level: 1,
    tags: ['construction', 'shapes', 'ellipse'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    prerequisites: [11002],
    microChallenges: mc(
      'cylinders-only',
      { en: 'Practice 6 ellipses at different tilts', ru: '6 эллипсов под разным наклоном' },
      { en: 'Block 3 objects with cylinders', ru: '3 предмета цилиндрическими блоками' },
      { en: 'Compare to cube version — note differences', ru: 'Сравни с кубической версией' },
      [4, 8, 3],
    ),
  },
  {
    id: 11004,
    category: 'anatomy',
    difficulty: 'novice',
    inspiredBy: 'prokotv',
    source: 'Proko (YouTube)',
    title: { en: '5 Hand Silhouettes', ru: '5 силуэтов руки' },
    description: {
      en: 'Draw 5 hand silhouettes from imagination or photo — shape only, no interior lines.',
      ru: '5 силуэтов руки с воображения или по фото — только форма, без внутренних линий.',
    },
    xp: 50,
    estimatedTime: 22,
    min_level: 1,
    tags: ['hands', 'silhouette', 'construction'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'hand-silhouette',
      { en: '3 tiny thumb-only shapes', ru: '3 мини-формы большого пальца' },
      { en: '5 hand silhouettes, varied angles', ru: '5 силуэтов рук, разные ракурсы' },
      { en: 'Fill one silhouette with 3 mass groups', ru: 'В одном силуэте — 3 массы' },
      [4, 12, 6],
    ),
  },
  {
    id: 11005,
    category: 'storytelling',
    difficulty: 'intermediate',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Storyboard Beat: 6 Panels', ru: 'Сториборд: 6 панелей' },
    description: {
      en: 'Thumbnail storyboard for one short beat (6 panels). No clean lineart — readability only.',
      ru: 'Мини-раскадровка одного бита (6 панелей). Без чистовой линии — только читаемость.',
    },
    xp: 72,
    estimatedTime: 40,
    min_level: 4,
    tags: ['panels', 'storyboard', 'pipeline'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 14,
    microChallenges: mc(
      'storyboard-6',
      { en: 'Write 1-sentence story beat', ru: 'Один бит истории — одно предложение' },
      { en: '6 rough panel thumbnails', ru: '6 грубых панелей-эскизов' },
      { en: 'Arrow flow + label camera on 2 panels', ru: 'Стрелки потока + камера на 2 панелях' },
      [5, 25, 10],
    ),
  },
  {
    id: 11006,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: '20 Construction Sketches', ru: '20 построительных набросков' },
    description: {
      en: '20 quick object sketches (1–2 min each). Focus on major masses, not detail.',
      ru: '20 быстрых набросков предметов (1–2 мин). Крупные массы, без деталей.',
    },
    xp: 55,
    estimatedTime: 35,
    min_level: 1,
    tags: ['construction', 'quantity', 'practice'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'construction-20',
      { en: '5 warmup circles and boxes', ru: '5 разминочных кругов и кубов' },
      { en: '15 object construction sketches', ru: '15 построительных набросков' },
      { en: 'Circle 3 favorites for tomorrow', ru: 'Обведи 3 лучших для повтора' },
      [5, 25, 5],
    ),
  },
  {
    id: 11007,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: 'Contour Still Life: 10 Min', ru: 'Контур с натуры: 10 минут' },
    description: {
      en: 'One still-life object — continuous contour, no lifting pencil, 10 minutes.',
      ru: 'Один предмет с натуры — непрерывный контур, не отрывая карандаш, 10 минут.',
    },
    xp: 38,
    estimatedTime: 12,
    min_level: 1,
    tags: ['contour', 'observation'],
    medium: 'traditional',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'contour-10',
      { en: '2 min blind contour warmup', ru: '2 мин слепой контур — разминка' },
      { en: '10 min continuous contour main', ru: '10 мин основной непрерывный контур' },
      { en: 'Trace problem areas lightly once', ru: 'Один раз пройди проблемные зоны' },
      [2, 10, 2],
    ),
  },
  {
    id: 11008,
    category: 'drawing',
    difficulty: 'intermediate',
    inspiredBy: 'drawlikeasir',
    source: 'Draw Like a Sir (YouTube)',
    title: { en: 'Simplify 5 Objects to Shapes', ru: 'Упрости 5 предметов до форм' },
    description: {
      en: 'Draw 5 objects as 3-shape max breakdowns (sphere/box/cylinder). Label each shape.',
      ru: '5 предметов — макс. 3 формы (шар/куб/цилиндр). Подпиши каждую форму.',
    },
    xp: 58,
    estimatedTime: 28,
    min_level: 3,
    tags: ['simplify', 'construction', 'shapes'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'simplify-5',
      { en: 'Pick 5 reference objects', ru: 'Выбери 5 референсов' },
      { en: 'Shape breakdown for all 5', ru: 'Разбор на формы для всех 5' },
      { en: 'Redraw 1 in exaggerated cartoon simplify', ru: '1 предмет — преувеличенное упрощение' },
      [4, 18, 6],
    ),
  },
  {
    id: 11009,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'samdoesarts',
    source: 'SamDoesArts (YouTube)',
    title: { en: '12 Ellipses in Space', ru: '12 эллипсов в пространстве' },
    description: {
      en: 'Draw 12 ellipses as circles in perspective — top, side, steep tilt. Closed and smooth.',
      ru: '12 эллипсов как круги в перспективе — сверху, сбоку, крутой наклон. Замкнутые и плавные.',
    },
    xp: 46,
    estimatedTime: 20,
    min_level: 1,
    tags: ['ellipse', 'perspective', 'quantity'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'ellipse-12',
      { en: '4 ghosted ellipses warmup', ru: '4 эллипса «призраком»' },
      { en: '12 ellipses varied tilt', ru: '12 эллипсов, разный наклон' },
      { en: 'Turn 3 into cylinder stubs', ru: '3 преврати в цилиндры' },
      [4, 12, 4],
    ),
  },
  {
    id: 11010,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'prokotv',
    source: 'Proko (YouTube)',
    title: { en: '8 Gestures at 60 Seconds', ru: '8 жестов по 60 секунд' },
    description: {
      en: '8 figure gestures, 60 seconds each. Capture line of action; ignore fingers and faces.',
      ru: '8 жестовых фигур по 60 сек. Линия действия; без пальцев и лица.',
    },
    xp: 44,
    estimatedTime: 14,
    min_level: 1,
    tags: ['gesture', 'figure', 'speed'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'gesture-60',
      { en: '2 one-minute scribble warmups', ru: '2 минуты свободной разминки' },
      { en: '8 × 60 sec gestures', ru: '8 жестов по 60 сек' },
      { en: 'Star 2 — note what reads best', ru: 'Отметь 2 лучших — что читается' },
      [2, 10, 2],
    ),
  },
  {
    id: 11011,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'keshart',
    source: 'KeshArt (YouTube)',
    title: { en: 'Mileage: 30 Loose Lines', ru: 'Mileage: 30 свободных линий' },
    description: {
      en: 'Fill one page with 30 confident strokes — varied direction and pressure. No subjects required.',
      ru: 'Страница из 30 уверенных штрихов — направление и нажим. Без конкретных объектов.',
    },
    xp: 35,
    estimatedTime: 12,
    min_level: 1,
    tags: ['line-control', 'warmup', 'practice'],
    medium: 'traditional',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'mileage-30',
      { en: '10 hairline strokes', ru: '10 едва видимых штрихов' },
      { en: '20 medium-to-heavy strokes', ru: '20 штрихов среднего и сильного нажима' },
      { en: 'Combine into 3 abstract shapes', ru: 'Собери 3 абстрактные формы' },
      [3, 7, 2],
    ),
  },
  {
    id: 11012,
    category: 'anatomy',
    difficulty: 'novice',
    inspiredBy: 'linessensei',
    source: 'Lines Sensei (YouTube)',
    title: { en: 'Head Construction: 4 Angles', ru: 'Построение головы: 4 ракурса' },
    description: {
      en: 'Same character head — front, 3/4, profile, down angle. Construction lines visible.',
      ru: 'Одна голова — фронт, 3/4, профиль, сверху. Видны построительные линии.',
    },
    xp: 62,
    estimatedTime: 32,
    min_level: 2,
    tags: ['head', 'construction', 'portrait'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'head-4angle',
      { en: '1 Loomis ball + cross front view', ru: '1 шар Loomis + крест — фронт' },
      { en: '3/4 and profile construction', ru: '3/4 и профиль — построение' },
      { en: 'Down angle + check proportions', ru: 'Ракурс сверху + проверка пропорций' },
      [8, 18, 6],
    ),
  },
  {
    id: 11013,
    category: 'anatomy',
    difficulty: 'intermediate',
    inspiredBy: 'kaycemcrew',
    source: 'Kaycem Crew (YouTube)',
    title: { en: '6 Foreshortened Limbs', ru: '6 конечностей в ракурсе' },
    description: {
      en: 'Draw 6 arms or legs with strong foreshortening — cylinders and overlap, no full bodies.',
      ru: '6 рук или ног с сильным ракурсом — цилиндры и перекрытие, без полных тел.',
    },
    xp: 78,
    estimatedTime: 38,
    min_level: 5,
    tags: ['foreshortening', 'perspective', 'limbs'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'foreshort-limb',
      { en: '3 cylinder drills pointing at viewer', ru: '3 цилиндра «в камеру»' },
      { en: '6 foreshortened limbs', ru: '6 конечностей в ракурсе' },
      { en: 'Add overlap lines on 2 best', ru: 'Линии перекрытия на 2 лучших' },
      [6, 24, 8],
    ),
  },
  {
    id: 11014,
    category: 'anatomy',
    difficulty: 'novice',
    inspiredBy: 'animecharlie',
    source: 'Anime Charlie (YouTube)',
    title: { en: '5 Torso Gesture Blocks', ru: '5 жестовых блоков торса' },
    description: {
      en: '5 torso gestures — rib cage + pelvis as simple boxes, 2 min each.',
      ru: '5 жестов торса — грудная клетка и таз кубами, по 2 мин.',
    },
    xp: 48,
    estimatedTime: 18,
    min_level: 1,
    tags: ['torso', 'gesture', 'figure'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'torso-gesture',
      { en: '2 box ribcage/pelvis pairs', ru: '2 пары кубов грудь/таз' },
      { en: '5 timed torso gestures', ru: '5 жестов торса по таймеру' },
      { en: 'Connect best with spine line', ru: 'Линия позвоночника на лучшем' },
      [3, 12, 3],
    ),
  },
  {
    id: 11015,
    category: 'anatomy',
    difficulty: 'novice',
    inspiredBy: 'stevenmichaelhampton',
    source: 'Steven Michael Hampton (YouTube)',
    title: { en: '6 Head Gesture Sketches', ru: '6 жестовых эскизов головы' },
    description: {
      en: '6 head gestures emphasizing rhythm and tilt — no features, mass and axis only.',
      ru: '6 жестов головы — ритм и наклон, без черт, только массы и оси.',
    },
    xp: 46,
    estimatedTime: 16,
    min_level: 1,
    tags: ['head', 'gesture', 'rhythm'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'head-gesture-6',
      { en: '3 axis lines different tilts', ru: '3 оси с разным наклоном' },
      { en: '6 head mass gestures', ru: '6 жестов масс головы' },
      { en: 'Add jaw wedge on 2', ru: 'Клин челюсти на 2 эскизах' },
      [3, 10, 3],
    ),
  },
  {
    id: 11016,
    category: 'drawing',
    difficulty: 'intermediate',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: '15 Cross-Contour Forms', ru: '15 форм с перекрёстным контуром' },
    description: {
      en: 'On 15 simple forms, wrap cross-contour lines to show volume (fruit, limbs, props).',
      ru: 'На 15 простых формах — линии перекрёстного контура для объёма.',
    },
    xp: 68,
    estimatedTime: 35,
    min_level: 4,
    tags: ['contour', 'form', 'quantity'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'cross-contour-15',
      { en: '3 sphere cross-contours', ru: '3 сферы с перекрёстным контуром' },
      { en: '12 more forms with contours', ru: 'Ещё 12 форм с контурами' },
      { en: 'Shade one using contours only', ru: 'Тон на одной — только контуры' },
      [5, 25, 5],
    ),
  },
  {
    id: 11017,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: 'Blind Contour × 3 (5 Min)', ru: 'Слепой контур × 3 (по 5 мин)' },
    description: {
      en: 'Three 5-minute blind contours of the same object — compare improvement.',
      ru: 'Три слепых контура одного предмета по 5 мин — сравни прогресс.',
    },
    xp: 40,
    estimatedTime: 18,
    min_level: 1,
    tags: ['contour', 'observation', 'practice'],
    medium: 'traditional',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'blind-3',
      { en: 'Set up object + blind contour #1', ru: 'Предмет + слепой контур №1' },
      { en: 'Blind contours #2 and #3', ru: 'Слепые контуры №2 и №3' },
      { en: 'One peek contour overlay in color pencil', ru: 'Один контур «с подглядыванием» цветным карандашом' },
      [5, 10, 3],
    ),
  },
  {
    id: 11018,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'drawlikeasir',
    source: 'Draw Like a Sir (YouTube)',
    title: { en: '12 Box Construction Objects', ru: '12 предметов из кубов' },
    description: {
      en: 'Draw 12 small objects using box construction only — 2 min each.',
      ru: '12 мелких предметов только кубическим построением — по 2 мин.',
    },
    xp: 52,
    estimatedTime: 28,
    min_level: 1,
    tags: ['construction', 'quantity', 'shapes'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'box-12',
      { en: '4 freehand boxes in perspective', ru: '4 куба от руки в перспективе' },
      { en: '12 box-built objects', ru: '12 предметов из кубов' },
      { en: 'Pick 2 — add one cast shadow', ru: '2 лучших — одна падающая тень' },
      [5, 20, 3],
    ),
  },
  {
    id: 11019,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: 'Drill Rotation: Lines & Circles', ru: 'Ротация дриллов: линии и круги' },
    description: {
      en: 'Page 1: 40 straight lines. Page 2: 30 circles/ellipses. Page 3: 10 boxes. No erasing.',
      ru: 'Стр.1: 40 прямых. Стр.2: 30 кругов/эллипсов. Стр.3: 10 кубов. Без ластика.',
    },
    xp: 48,
    estimatedTime: 25,
    min_level: 1,
    tags: ['line-control', 'warmup', 'drills'],
    medium: 'traditional',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'drill-rotate',
      { en: '40 lines — varied angle and pressure', ru: '40 линий — угол и нажим' },
      { en: '30 circles and ellipses', ru: '30 кругов и эллипсов' },
      { en: '10 boxes — connect best 3 into one object', ru: '10 кубов — 3 лучших в один объект' },
      [8, 12, 5],
    ),
  },
  {
    id: 11020,
    category: 'anatomy',
    difficulty: 'intermediate',
    inspiredBy: 'kaycemcrew',
    source: 'Kaycem Crew (YouTube)',
    title: { en: '8 Dynamic Pose Thumbnails', ru: '8 эскизов динамичных поз' },
    description: {
      en: '8 small figure thumbnails with strong line of action — 3 min each, no details.',
      ru: '8 мини-фигур с сильной линией действия — по 3 мин, без деталей.',
    },
    xp: 70,
    estimatedTime: 30,
    min_level: 4,
    tags: ['gesture', 'motion', 'figure'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'dynamic-8',
      { en: '2 stick figures — extreme poses', ru: '2 палочки — экстремальные позы' },
      { en: '8 dynamic thumbnails', ru: '8 динамичных эскизов' },
      { en: 'Pick 1 — add 3 mass volumes', ru: '1 лучший — 3 объёмные массы' },
      [4, 22, 4],
    ),
  },
]
