/** Packs C, D, E — anime pipeline, color/design, study habits */
import { mc, type QuestDraft } from './youtube-quest-helpers.ts'

export const PACK_C: QuestDraft[] = [
  {
    id: 11039,
    category: 'storytelling',
    difficulty: 'intermediate',
    inspiredBy: 'sakugafoundry',
    source: 'Sakuga Foundry (YouTube)',
    title: { en: 'Layout Thumbnails: 3 Angles', ru: 'Layout: 3 ракурса' },
    description: {
      en: 'One scene — 3 layout thumbnails (wide, medium, close). No clean lineart.',
      ru: 'Одна сцена — 3 layout-миниатюры (общий, средний, крупный). Без чистовой линии.',
    },
    xp: 70,
    estimatedTime: 35,
    min_level: 5,
    tags: ['layout', 'camera', 'pipeline'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 14,
    microChallenges: mc(
      'layout-3',
      { en: 'Script beat — 1 sentence', ru: 'Бит сценария — 1 предложение' },
      { en: '3 layout thumbs', ru: '3 layout-миниатюры' },
      { en: 'Horizon line on all 3', ru: 'Линия горизонта на всех 3' },
      [5, 22, 8],
    ),
  },
  {
    id: 11040,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'sakugafoundry',
    source: 'Sakuga Foundry (YouTube)',
    title: { en: 'Genga Study: Timing Only', ru: 'Genga: только тайминг' },
    description: {
      en: 'From one reference key: trace motion paths and timing notes only — no final ink or color.',
      ru: 'По одному референсу: траектории и пометки тайминга — без чистовой линии и цвета.',
    },
    xp: 115,
    estimatedTime: 50,
    min_level: 11,
    tags: ['genga', 'timing', 'pipeline'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 21,
    microChallenges: mc(
      'genga-timing',
      { en: 'Pick reference — note frame count', ru: 'Референс — число кадров' },
      { en: 'Paths and spacing notes', ru: 'Траектории и spacing' },
      { en: '3 timing notes for holds', ru: '3 пометки hold' },
      [8, 32, 10],
    ),
  },
  {
    id: 11041,
    category: 'storytelling',
    difficulty: 'intermediate',
    inspiredBy: 'spywis',
    source: "Spywi's Mind Palace (YouTube)",
    title: { en: 'Efficiency Board: Static + 1 Move', ru: 'Efficiency: статичный фон + 1 движение' },
    description: {
      en: 'Plan one shot: static background layer + one moving element + optional FX loop notes.',
      ru: 'Один кадр: статичный фон + один движущийся элемент + заметки по FX-лупу.',
    },
    xp: 68,
    estimatedTime: 32,
    min_level: 5,
    tags: ['efficiency', 'layers', 'pipeline'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 14,
    microChallenges: mc(
      'efficiency-board',
      { en: 'Layer list diagram', ru: 'Диаграмма слоёв' },
      { en: 'BG paint-over static', ru: 'Фон — статичная заливка' },
      { en: 'Moving element keys (4)', ru: '4 ключа движущегося элемента' },
      [6, 18, 8],
    ),
  },
  {
    id: 11042,
    category: 'storytelling',
    difficulty: 'novice',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Storyboard Pass: 6 Panels', ru: 'Сториборд: 6 панелей (чистый)' },
    description: {
      en: '6-panel storyboard for a 10-second beat. Focus on clarity, not polish.',
      ru: '6 панелей на 10-секундный бит. Ясность, не полировка.',
    },
    xp: 55,
    estimatedTime: 30,
    min_level: 2,
    tags: ['storyboard', 'panels', 'pipeline'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'sb-6-pass',
      { en: 'Beat outline in 3 bullets', ru: 'Бит в 3 пунктах' },
      { en: '6 panel thumbs', ru: '6 панелей' },
      { en: 'Number panels for timing', ru: 'Нумерация панелей по таймингу' },
      [4, 20, 6],
    ),
  },
  {
    id: 11043,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Layout Sheet: 4 Thumbnails', ru: 'Layout: 4 миниатюры одной сцены' },
    description: {
      en: 'After storyboard: 4 layout compositions for one scene — perspective and staging.',
      ru: 'После сториборда: 4 layout-композиции одной сцены — перспектива и staging.',
    },
    xp: 95,
    estimatedTime: 45,
    min_level: 10,
    tags: ['layout', 'staging', 'pipeline'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 21,
    prerequisites: [11042],
    microChallenges: mc(
      'layout-4',
      { en: 'Pick panel to expand', ru: 'Выбери панель для развития' },
      { en: '4 layout variations', ru: '4 варианта layout' },
      { en: 'Mark camera height on best', ru: 'Высота камеры на лучшем' },
      [6, 30, 9],
    ),
  },
  {
    id: 11044,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'sakugafoundry',
    source: 'Sakuga Foundry (YouTube)',
    title: { en: 'Key Pose Silhouette Only', ru: 'Ключевая поза: только силуэт' },
    description: {
      en: '3 key poses as black silhouettes — readable action, no interior detail.',
      ru: '3 ключевые позы чёрным силуэтом — читаемое действие, без деталей.',
    },
    xp: 72,
    estimatedTime: 28,
    min_level: 5,
    tags: ['silhouette', 'staging', 'keys'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'key-silhouette',
      { en: '3 rough pose scribbles', ru: '3 грубых позы' },
      { en: '3 filled silhouettes', ru: '3 залитых силуэта' },
      { en: 'Negative space check', ru: 'Проверка негативного пространства' },
      [5, 18, 5],
    ),
  },
  {
    id: 11045,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'animationschool_live',
    source: 'Animation School Live (YouTube)',
    title: { en: 'In-Between Planning Sheet', ru: 'Лист планирования in-between' },
    description: {
      en: 'One key pair + chart where in-betweens go (numbers only). Draw 3 in-betweens.',
      ru: 'Пара ключей + схема in-between (номера). Нарисуй 3 промежуточных.',
    },
    xp: 78,
    estimatedTime: 32,
    min_level: 6,
    tags: ['inbetweens', 'charts', 'pipeline'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'ib-plan',
      { en: '2 keys + spacing chart', ru: '2 ключа + график spacing' },
      { en: '3 in-betweens', ru: '3 in-between' },
      { en: 'Flip and fix one pop', ru: 'Флип — исправь один рывок' },
      [6, 20, 6],
    ),
  },
  {
    id: 11046,
    category: 'storytelling',
    difficulty: 'intermediate',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Color Script: 6 Swatches', ru: 'Color script: 6 образцов' },
    description: {
      en: '6 swatches defining mood for one scene — label role (BG, skin, accent).',
      ru: '6 образцов настроения сцены — роль (фон, кожа, акцент).',
    },
    xp: 60,
    estimatedTime: 25,
    min_level: 4,
    tags: ['color', 'mood', 'pipeline'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'color-script',
      { en: 'Mood words — 3 adjectives', ru: '3 прилагательных настроения' },
      { en: '6 swatches', ru: '6 образцов' },
      { en: 'Apply to 1 thumbnail', ru: 'На 1 миниатюру' },
      [4, 15, 6],
    ),
  },
  {
    id: 11047,
    category: 'storytelling',
    difficulty: 'advanced',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Animatic: 12 Panel Timing', ru: 'Аниматик: 12 панелей' },
    description: {
      en: '12 panels with hold durations written (frames or seconds). No full animation.',
      ru: '12 панелей с длительностью hold (кадры или секунды). Без полной анимации.',
    },
    xp: 105,
    estimatedTime: 55,
    min_level: 9,
    tags: ['animatic', 'pacing', 'pipeline'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 21,
    prerequisites: [11042],
    microChallenges: mc(
      'animatic-12',
      { en: '6 key story beats', ru: '6 ключевых битов' },
      { en: '12 panels with timing', ru: '12 панелей с таймингом' },
      { en: 'Total duration sum check', ru: 'Проверка суммарной длительности' },
      [8, 38, 9],
    ),
  },
  {
    id: 11048,
    category: 'storytelling',
    difficulty: 'master',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Pipeline Checklist: One Shot', ru: 'Чеклист пайплайна: один шот' },
    description: {
      en: 'Fill pipeline checklist (plan → board → layout → key) for one shot. Checkboxes + 1 thumb each stage.',
      ru: 'Чеклист пайплайна (план → борд → layout → ключ) для одного шота. Галочки + 1 эскиз на этап.',
    },
    xp: 180,
    estimatedTime: 90,
    min_level: 15,
    tags: ['pipeline', 'production', 'industry'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 30,
    prerequisites: [11043, 11047],
    microChallenges: mc(
      'pipeline-check',
      { en: 'Plan + storyboard thumb', ru: 'План + эскиз сториборда' },
      { en: 'Layout + key silhouette', ru: 'Layout + силуэт ключа' },
      { en: 'Review gaps in checklist', ru: 'Пробелы в чеклисте' },
      [20, 45, 25],
    ),
  },
  {
    id: 11049,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'mother_is_ape',
    source: 'mother is ape (YouTube)',
    title: { en: 'Style Study: 3 Key Frames', ru: 'Стилевой разбор: 3 ключа' },
    description: {
      en: 'Copy 3 key frames from a reference clip — match line weight and proportions only.',
      ru: 'Скопируй 3 ключа с референса — вес линии и пропорции, без цвета.',
    },
    xp: 75,
    estimatedTime: 38,
    min_level: 5,
    tags: ['study', 'keys', 'anime'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'style-3',
      { en: 'Pick 3 ref frames', ru: '3 кадра референса' },
      { en: 'Line-only copies', ru: 'Копии только линией' },
      { en: 'Note 3 style rules', ru: '3 правила стиля' },
      [5, 28, 5],
    ),
  },
  {
    id: 11050,
    category: 'storytelling',
    difficulty: 'novice',
    inspiredBy: 'animationschool_live',
    source: 'Animation School Live (YouTube)',
    title: { en: 'Desk Study Thumbnail', ru: 'Эскиз рабочего места' },
    description: {
      en: 'Thumbnail of your workspace from memory — 10 min. Label 5 zones (draw, ref, tools).',
      ru: 'Эскиз рабочего места по памяти — 10 мин. 5 зон (рисунок, реф, инструменты).',
    },
    xp: 35,
    estimatedTime: 12,
    min_level: 1,
    tags: ['workflow', 'study_plan'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'desk-thumb',
      { en: '5 min rough boxes layout', ru: '5 мин — кубы планировки' },
      { en: 'Label zones', ru: 'Подписи зон' },
      { en: 'One improvement note', ru: 'Одна идея улучшения' },
      [4, 6, 2],
    ),
  },
]

export const PACK_D: QuestDraft[] = [
  {
    id: 11051,
    category: 'drawing',
    difficulty: 'intermediate',
    inspiredBy: 'marcobucci',
    source: 'Marco Bucci (YouTube)',
    title: { en: 'Shadow Color: 3 Light Setups', ru: 'Цвет тени: 3 схемы света' },
    description: {
      en: 'One simple object — paint 3 versions with different light direction. Shadow hue shifts required.',
      ru: 'Один простой объект — 3 варианта света. Сдвиг оттенка тени обязателен.',
    },
    xp: 82,
    estimatedTime: 40,
    min_level: 5,
    tags: ['shadows', 'color', 'lighting'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'shadow-3',
      { en: 'Line object once', ru: 'Линия объекта один раз' },
      { en: '3 flat color passes', ru: '3 плоских прохода цвета' },
      { en: 'Label warm/cool shadow', ru: 'Подпись тёплой/холодной тени' },
      [6, 28, 6],
    ),
  },
  {
    id: 11052,
    category: 'drawing',
    difficulty: 'intermediate',
    inspiredBy: 'sinixdesign',
    source: 'Sinix Design (YouTube)',
    title: { en: 'Composition: 6 Thumbnails', ru: 'Композиция: 6 миниатюр' },
    description: {
      en: 'Same subject — 6 compositions with different focal points. 3 min each.',
      ru: 'Один сюжет — 6 композиций с разным фокусом. По 3 мин.',
    },
    xp: 70,
    estimatedTime: 32,
    min_level: 4,
    tags: ['composition', 'focal', 'thumbnails'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'comp-6',
      { en: '2 rule-of-thirds tests', ru: '2 теста правила третей' },
      { en: '6 thumbnails', ru: '6 миниатюр' },
      { en: 'Star best — why in 1 sentence', ru: 'Лучшая — почему, 1 предложение' },
      [5, 22, 5],
    ),
  },
  {
    id: 11053,
    category: 'character_design',
    difficulty: 'novice',
    inspiredBy: 'rossdraws',
    source: 'Ross Draws (YouTube)',
    title: { en: 'Silhouette Lineup: 8 Characters', ru: 'Линейка силуэтов: 8 персонажей' },
    description: {
      en: '8 character silhouettes sharing one trait (hat, cape, etc.) — black fill only.',
      ru: '8 силуэтов с общей чертой (шляпа, плащ…) — только заливка.',
    },
    xp: 58,
    estimatedTime: 28,
    min_level: 2,
    tags: ['silhouette', 'design', 'shape_language'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'sil-8',
      { en: 'Define shared trait', ru: 'Общая черта' },
      { en: '8 silhouettes', ru: '8 силуэтов' },
      { en: 'Pick 2 to rough sketch', ru: '2 — грубый скетч' },
      [4, 20, 4],
    ),
  },
  {
    id: 11054,
    category: 'drawing',
    difficulty: 'advanced',
    inspiredBy: 'marcobucci',
    source: 'Marco Bucci (YouTube)',
    title: { en: 'Limited Palette: 3 Colors', ru: 'Палитра из 3 цветов' },
    description: {
      en: 'Illustrate one scene using only 3 colors (+ black/white allowed).',
      ru: 'Одна сцена только 3 цвета (+ чёрный/белый).',
    },
    xp: 95,
    estimatedTime: 45,
    min_level: 8,
    tags: ['color', 'harmony', 'constraint'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 21,
    microChallenges: mc(
      'palette-3',
      { en: 'Pick 3 swatches + mood', ru: '3 образца + настроение' },
      { en: 'Flat block-in', ru: 'Плоский block-in' },
      { en: 'One accent pass', ru: 'Один проход акцента' },
      [6, 30, 9],
    ),
  },
  {
    id: 11055,
    category: 'drawing',
    difficulty: 'intermediate',
    inspiredBy: 'niroxious',
    source: 'niroxious (YouTube)',
    title: { en: 'Skin Tone Swatches: 5', ru: 'Оттенки кожи: 5 образцов' },
    description: {
      en: '5 skin tone swatches for one lighting — label highlight/mid/shadow.',
      ru: '5 образцов кожи при одном свете — highlight/mid/shadow.',
    },
    xp: 65,
    estimatedTime: 30,
    min_level: 4,
    tags: ['skin', 'color', 'render'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'skin-5',
      { en: 'Base mid tone', ru: 'Базовый средний тон' },
      { en: '5 swatches', ru: '5 образцов' },
      { en: 'Apply to small portrait', ru: 'На мини-портрет' },
      [5, 18, 7],
    ),
  },
  {
    id: 11056,
    category: 'anatomy',
    difficulty: 'intermediate',
    inspiredBy: 'niroxious',
    source: 'niroxious (YouTube)',
    title: { en: 'Fold Study: 6 Sketches', ru: 'Складки: 6 этюдов' },
    description: {
      en: '6 fabric fold sketches — tension vs compression labeled.',
      ru: '6 зарисовок складок — натяжение vs сжатие с подписями.',
    },
    xp: 72,
    estimatedTime: 35,
    min_level: 5,
    tags: ['folds', 'fabric', 'drapery'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'fold-6',
      { en: '2 cylinder cloth wraps', ru: '2 оборота ткани на цилиндре' },
      { en: '6 fold studies', ru: '6 этюдов складок' },
      { en: 'One on figure limb', ru: 'Одна на конечности' },
      [5, 24, 6],
    ),
  },
  {
    id: 11057,
    category: 'environment',
    difficulty: 'novice',
    inspiredBy: 'samdoesarts',
    source: 'SamDoesArts (YouTube)',
    title: { en: 'Room Corner Perspective', ru: 'Угол комнаты в перспективе' },
    description: {
      en: 'Draw one room corner in 2-point perspective — boxes only, no props detail.',
      ru: 'Угол комнаты в 2-точечной перспективе — только кубы, без деталей.',
    },
    xp: 55,
    estimatedTime: 28,
    min_level: 2,
    tags: ['perspective', 'interior'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'room-corner',
      { en: '2 VP setup on page', ru: '2 точки схода' },
      { en: 'Floor + 2 walls boxes', ru: 'Пол + 2 стены кубами' },
      { en: 'One furniture box', ru: 'Один предмет-мебель кубом' },
      [6, 18, 4],
    ),
  },
  {
    id: 11058,
    category: 'character_design',
    difficulty: 'intermediate',
    inspiredBy: 'rossdraws',
    source: 'Ross Draws (YouTube)',
    title: { en: 'Portrait Lighting Study', ru: 'Портрет: один источник света' },
    description: {
      en: 'One portrait — single light source, 3-value block-in only.',
      ru: 'Портрет — один источник, block-in в 3 тона.',
    },
    xp: 78,
    estimatedTime: 38,
    min_level: 5,
    tags: ['lighting', 'portrait', 'value'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'portrait-light',
      { en: 'Placement diagram', ru: 'Схема света' },
      { en: '3-value block-in', ru: 'Block-in 3 тона' },
      { en: 'Soft edge on terminator', ru: 'Мягкий край терминатора' },
      [5, 25, 8],
    ),
  },
  {
    id: 11059,
    category: 'character_design',
    difficulty: 'advanced',
    inspiredBy: 'ahmedaldoori',
    source: 'Ahmed Aldoori (YouTube)',
    title: { en: 'Value Portrait Blocking', ru: 'Портрет: value blocking' },
    description: {
      en: 'Portrait in 5 values only — no lineart finish. Readable likeness optional.',
      ru: 'Портрет в 5 тонах — без чистовой линии. Сходство по желанию.',
    },
    xp: 110,
    estimatedTime: 50,
    min_level: 10,
    tags: ['value', 'portrait', 'render'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 21,
    microChallenges: mc(
      'value-block',
      { en: 'Big shape map', ru: 'Карта крупных форм' },
      { en: '5-value pass', ru: '5 тонов' },
      { en: 'Fix one muddy zone', ru: 'Исправь одну «грязную» зону' },
      [8, 35, 7],
    ),
  },
  {
    id: 11060,
    category: 'character_design',
    difficulty: 'novice',
    inspiredBy: 'aaronblaiseart',
    source: 'Aaron Blaise (YouTube)',
    title: { en: 'Animal Gesture: 6 Sketches', ru: 'Жест животного: 6 эскизов' },
    description: {
      en: '6 animal gestures (any species) — 2 min each, line of action emphasized.',
      ru: '6 жестов животных — по 2 мин, линия действия.',
    },
    xp: 52,
    estimatedTime: 20,
    min_level: 1,
    tags: ['animal', 'gesture', 'creatures'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'animal-gesture',
      { en: '2 cat/dog scribbles', ru: '2 кота/собаки-наброска' },
      { en: '6 gestures', ru: '6 жестов' },
      { en: 'Masses on 1 favorite', ru: 'Массы на лучшем' },
      [3, 14, 3],
    ),
  },
  {
    id: 11061,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'ytartschool',
    source: 'YT Art School (YouTube)',
    title: { en: 'Color Wheel Harmony Page', ru: 'Круг цвета и гармонии' },
    description: {
      en: 'Draw color wheel + 3 harmony schemes (complementary, analogous, triadic) with notes.',
      ru: 'Круг цвета + 3 схемы гармонии с пометками.',
    },
    xp: 48,
    estimatedTime: 25,
    min_level: 1,
    tags: ['color', 'harmony', 'hue'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'wheel-harmony',
      { en: '12-step wheel', ru: 'Круг 12 шагов' },
      { en: '3 harmony mini swatches', ru: '3 мини-гармонии' },
      { en: '1 tiny scene using triadic', ru: 'Мини-сцена — триада' },
      [8, 12, 5],
    ),
  },
  {
    id: 11062,
    category: 'environment',
    difficulty: 'intermediate',
    inspiredBy: 'marcobucci',
    source: 'Marco Bucci (YouTube)',
    title: { en: 'Mood Thumbnails: 4', ru: 'Настроение: 4 миниатюры' },
    description: {
      en: 'Same location — 4 mood variants (dawn, storm, calm, neon) — value only.',
      ru: 'Одно место — 4 настроения (рассвет, шторм, штиль, неон) — только тон.',
    },
    xp: 75,
    estimatedTime: 36,
    min_level: 5,
    tags: ['mood', 'lighting', 'environment'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'mood-4',
      { en: '1 base layout thumb', ru: '1 базовый layout' },
      { en: '4 value moods', ru: '4 тоновых настроения' },
      { en: 'Label light direction each', ru: 'Направление света на каждом' },
      [6, 24, 6],
    ),
  },
  {
    id: 11063,
    category: 'character_design',
    difficulty: 'novice',
    inspiredBy: 'jazza',
    source: 'Jazza (YouTube)',
    title: { en: 'Costume Silhouettes: 5', ru: 'Костюм: 5 силуэтов' },
    description: {
      en: '5 costume silhouettes for one character archetype — vary shape language.',
      ru: '5 силуэтов костюма для одного архетипа — разный shape language.',
    },
    xp: 55,
    estimatedTime: 26,
    min_level: 2,
    tags: ['costume', 'silhouette', 'design'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'costume-5',
      { en: 'Archetype 3 words', ru: 'Архетип — 3 слова' },
      { en: '5 silhouettes', ru: '5 силуэтов' },
      { en: 'Color flare on 1', ru: 'Цветовой акцент на 1' },
      [4, 18, 4],
    ),
  },
  {
    id: 11064,
    category: 'character_design',
    difficulty: 'intermediate',
    inspiredBy: 'aleiriau',
    source: 'aleiriau (YouTube)',
    title: { en: 'Commission Breakdown Notes', ru: 'Разбор комиссии: заметки' },
    description: {
      en: 'Pick one illustration ref — write stage breakdown (sketch, line, color, polish) with times.',
      ru: 'Один референс иллюстрации — этапы (скетч, линия, цвет, полировка) с временем.',
    },
    xp: 68,
    estimatedTime: 30,
    min_level: 4,
    tags: ['process', 'study', 'commission'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 14,
    microChallenges: mc(
      'commission-notes',
      { en: 'Screenshot 4 stages', ru: '4 этапа — скрин/эскиз' },
      { en: 'Written time budget', ru: 'Бюджет времени' },
      { en: '1 stage practice 15 min', ru: '15 мин практики одного этапа' },
      [6, 18, 6],
    ),
  },
  {
    id: 11065,
    category: 'drawing',
    difficulty: 'advanced',
    inspiredBy: 'sinixdesign',
    source: 'Sinix Design (YouTube)',
    title: { en: 'Focal Point: 4 Versions', ru: 'Фокус: 4 версии' },
    description: {
      en: 'Same scene painted 4 ways — focal on different object each time.',
      ru: 'Одна сцена 4 раза — фокус на разном объекте.',
    },
    xp: 100,
    estimatedTime: 48,
    min_level: 9,
    tags: ['composition', 'focal', 'advanced'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 21,
    prerequisites: [11052],
    microChallenges: mc(
      'focal-4',
      { en: 'Grayscale block same layout', ru: 'Один layout — серый block' },
      { en: '4 focal variants', ru: '4 варианта фокуса' },
      { en: 'Blur/edge soft on non-focal', ru: 'Размытие вне фокуса' },
      [8, 32, 8],
    ),
  },
]

export const PACK_E: QuestDraft[] = [
  {
    id: 11066,
    category: 'drawing',
    difficulty: 'intermediate',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: 'Before/After Page', ru: 'Страница до/после' },
    description: {
      en: '20 min drawing → 10 min one corrective pass on same page. Upload both visible.',
      ru: '20 мин рисунок → 10 мин один исправительный проход. Загрузи оба на странице.',
    },
    xp: 70,
    estimatedTime: 32,
    min_level: 3,
    tags: ['feedback', 'study_plan', 'practice'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'before-after',
      { en: '20 min timed drawing', ru: '20 мин по таймеру' },
      { en: 'List 3 mistakes', ru: '3 ошибки списком' },
      { en: '10 min fix pass', ru: '10 мин исправлений' },
      [20, 5, 10],
    ),
  },
  {
    id: 11067,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'brokendraw',
    source: 'brokendraw (YouTube)',
    title: { en: 'Timed Failure Log: 3×5 Min', ru: 'Лог неудач: 3×5 мин' },
    description: {
      en: 'Three 5-minute attempts at same subject. Mark best and write why.',
      ru: 'Три попытки по 5 мин на один сюжет. Отметь лучшую и почему.',
    },
    xp: 42,
    estimatedTime: 18,
    min_level: 1,
    tags: ['study_plan', 'speed', 'feedback'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'fail-log',
      { en: 'Attempt 1 — 5 min', ru: 'Попытка 1 — 5 мин' },
      { en: 'Attempts 2–3', ru: 'Попытки 2–3' },
      { en: 'Write 2-sentence critique', ru: 'Критика в 2 предложениях' },
      [5, 10, 3],
    ),
  },
  {
    id: 11068,
    category: 'storytelling',
    difficulty: 'intermediate',
    inspiredBy: 'cgspeak',
    source: 'CGSpeak (YouTube)',
    title: { en: 'Reel Storyboard: 6 Frames', ru: 'Сториборд рила: 6 кадров' },
    description: {
      en: '6 frames planning a 30-second reel — label skill shown per frame.',
      ru: '6 кадров плана рила на 30 сек — навык на каждом кадре.',
    },
    xp: 72,
    estimatedTime: 35,
    min_level: 4,
    tags: ['portfolio', 'reel', 'study_plan'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 14,
    microChallenges: mc(
      'reel-6',
      { en: 'List 3 skills to show', ru: '3 навыка для показа' },
      { en: '6 frame thumbs', ru: '6 кадров' },
      { en: 'Order for impact', ru: 'Порядок для эффекта' },
      [5, 22, 8],
    ),
  },
  {
    id: 11069,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'keshart',
    source: 'KeshArt (YouTube)',
    title: { en: 'Study Timer Log', ru: 'Лог учебных сессий' },
    description: {
      en: 'Log 3 study sessions today (topic + minutes). Draw at least 15 min total.',
      ru: 'Запиши 3 сессии (тема + минуты). Минимум 15 мин рисования суммарно.',
    },
    xp: 38,
    estimatedTime: 20,
    min_level: 1,
    tags: ['study_plan', 'habits', 'practice'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'timer-log',
      { en: 'Session 1 — 5 min warmup', ru: 'Сессия 1 — 5 мин разминка' },
      { en: 'Session 2–3 logged', ru: 'Сессии 2–3 в логе' },
      { en: 'Tomorrow goal 1 line', ru: 'Цель на завтра — 1 строка' },
      [5, 10, 5],
    ),
  },
  {
    id: 11070,
    category: 'storytelling',
    difficulty: 'novice',
    inspiredBy: 'cgspeak',
    source: 'CGSpeak (YouTube)',
    title: { en: 'Self-Critique Checklist', ru: 'Чеклист самокритики' },
    description: {
      en: 'Apply 10-point checklist to one old drawing. Fix top 2 issues in 15 min.',
      ru: 'Чеклист из 10 пунктов на старый рисунок. Исправь 2 главные проблемы за 15 мин.',
    },
    xp: 45,
    estimatedTime: 22,
    min_level: 1,
    tags: ['feedback', 'study_plan'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'critique-10',
      { en: 'Print/write checklist', ru: 'Чеклист на бумаге' },
      { en: 'Score old work', ru: 'Оцени старую работу' },
      { en: '15 min fix top 2', ru: '15 мин — 2 исправления' },
      [5, 10, 7],
    ),
  },
  {
    id: 11071,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'ergojosh',
    source: 'ErgoJosh (YouTube)',
    title: { en: 'Desk Ergonomics Sketch + Notes', ru: 'Эргономика стола: эскиз и заметки' },
    description: {
      en: 'Sketch ideal desk setup top-down. List 5 ergonomic fixes for your space.',
      ru: 'Эскиз идеального стола сверху. 5 правок эргономики для твоего места.',
    },
    xp: 32,
    estimatedTime: 15,
    min_level: 1,
    tags: ['workflow', 'study_plan'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 30,
    microChallenges: mc(
      'ergo-desk',
      { en: '5 min current setup sketch', ru: '5 мин — текущая схема' },
      { en: 'Ideal setup diagram', ru: 'Идеальная схема' },
      { en: 'Implement 1 fix today', ru: '1 правка сегодня' },
      [5, 7, 3],
    ),
  },
  {
    id: 11072,
    category: 'storytelling',
    difficulty: 'intermediate',
    inspiredBy: 'cgspeak',
    source: 'CGSpeak (YouTube)',
    title: { en: 'Portfolio Pick: 5 Pieces', ru: 'Портфолио: выбор 5 работ' },
    description: {
      en: 'Choose 5 pieces for portfolio — write 1 sentence why each fits your goal.',
      ru: '5 работ для портфолио — по 1 предложению, почему каждая под цель.',
    },
    xp: 65,
    estimatedTime: 28,
    min_level: 4,
    tags: ['portfolio', 'career', 'study_plan'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 21,
    microChallenges: mc(
      'port-5',
      { en: 'Define portfolio goal', ru: 'Цель портфолио' },
      { en: 'Pick 5 works', ru: '5 работ' },
      { en: 'Cut 1 weakest — why', ru: 'Убери 1 слабую — почему' },
      [5, 18, 5],
    ),
  },
  {
    id: 11073,
    category: 'drawing',
    difficulty: 'novice',
    inspiredBy: 'keshart',
    source: 'KeshArt (YouTube)',
    title: { en: 'Milestone Journal: 3 Goals', ru: 'Журнал целей: 3 пункта' },
    description: {
      en: 'Write 3 art goals for 2 weeks + one 10-min drill per goal today.',
      ru: '3 цели на 2 недели + по одному 10-мин дриллу на цель сегодня.',
    },
    xp: 40,
    estimatedTime: 35,
    min_level: 1,
    tags: ['study_plan', 'roadmap', 'practice'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'milestone-3',
      { en: 'Write 3 SMART goals', ru: '3 SMART-цели' },
      { en: 'Drill goal 1 — 10 min', ru: 'Дрилл цели 1 — 10 мин' },
      { en: 'Drills goals 2–3', ru: 'Дриллы целей 2–3' },
      [5, 12, 18],
    ),
  },
]
