/** Pack B — 2D animation lab */
import { mc, type QuestDraft } from './youtube-quest-helpers.ts'

export const PACK_B: QuestDraft[] = [
  {
    id: 11021,
    category: 'animation',
    difficulty: 'novice',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Spacing Strip: 5 Ball Frames', ru: 'Spacing strip: 5 кадров мяча' },
    description: {
      en: 'Draw 5 frames of a ball bounce on one strip. Label slow-in and slow-out sections.',
      ru: '5 кадров отскока мяча на одной полосе. Подпиши slow-in и slow-out.',
    },
    xp: 52,
    estimatedTime: 20,
    min_level: 1,
    tags: ['spacing', 'timing', 'bounce'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'spacing-strip',
      { en: '2 key poses — apex and ground', ru: '2 ключа — вершина и земля' },
      { en: '5 frames with spacing marks', ru: '5 кадров с метками spacing' },
      { en: 'Label slow-in / slow-out arrows', ru: 'Стрелки slow-in / slow-out' },
      [4, 12, 4],
    ),
  },
  {
    id: 11022,
    category: 'animation',
    difficulty: 'novice',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Timing Chart Bounce', ru: 'График тайминга: отскок' },
    description: {
      en: 'Create a timing chart + 6-frame ball bounce. Chart and frames on one page.',
      ru: 'График тайминга + отскок из 6 кадров. График и кадры на одной странице.',
    },
    xp: 58,
    estimatedTime: 25,
    min_level: 2,
    tags: ['timing', 'charts', 'bounce'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    prerequisites: [11021],
    microChallenges: mc(
      'timing-chart',
      { en: 'Number chart 1–6 with hold notes', ru: 'График 1–6 с пометками hold' },
      { en: 'Draw 6 frames matching chart', ru: '6 кадров по графику' },
      { en: 'Flip test or export GIF loop', ru: 'Тест флипбука или GIF' },
      [6, 15, 4],
    ),
  },
  {
    id: 11023,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Anticipation + Overshoot Prop', ru: 'Anticipation + overshoot на реквизите' },
    description: {
      en: 'Animate a simple prop (cup, hammer) with anticipation before move and overshoot after stop — 8 keys.',
      ru: 'Простой реквизит (чашка, молоток): anticipation перед движением и overshoot после — 8 ключей.',
    },
    xp: 85,
    estimatedTime: 35,
    min_level: 5,
    tags: ['anticipation', 'overshoot', 'principles'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 14,
    prerequisites: [11022],
    microChallenges: mc(
      'anticip-overshoot',
      { en: '3 anticipation sketches', ru: '3 эскиза anticipation' },
      { en: '8 key poses with overshoot', ru: '8 ключей с overshoot' },
      { en: 'Hold 2 frames on anticipation', ru: '2 кадра hold на anticipation' },
      [6, 22, 7],
    ),
  },
  {
    id: 11024,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'howardwimshurst',
    source: 'Howard Wimshurst (YouTube)',
    title: { en: 'Impact Frame Trio', ru: 'Трио impact frames' },
    description: {
      en: 'One hit action: draw before / impact / after frames. Exaggerate smear on impact.',
      ru: 'Один удар: кадры до / impact / после. Преувеличь smear на impact.',
    },
    xp: 110,
    estimatedTime: 45,
    min_level: 10,
    tags: ['impact', 'smear', 'combat'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 21,
    prerequisites: [11023],
    microChallenges: mc(
      'impact-trio',
      { en: 'Silhouette 3 poses — before/hit/after', ru: '3 силуэта — до/удар/после' },
      { en: 'Impact frame with smear', ru: 'Impact-кадр со smear' },
      { en: 'Add speed lines or FX on 1 frame', ru: 'Линии скорости или FX на 1 кадре' },
      [8, 28, 9],
    ),
  },
  {
    id: 11025,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'tonikopantoja',
    source: 'Toniko Pantoja (YouTube)',
    title: { en: '4-Frame Dance Loop', ru: 'Танцевальный луп: 4 кадра' },
    description: {
      en: 'Simple character dance loop — 4 keys, test seamless loop export.',
      ru: 'Простой танцевальный луп — 4 ключа, проверь бесшовный цикл.',
    },
    xp: 75,
    estimatedTime: 32,
    min_level: 4,
    tags: ['loop', 'character', 'timing'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'dance-loop-4',
      { en: '2 pose keys — wide and narrow', ru: '2 ключа — широкая и узкая поза' },
      { en: '4-frame loop keys', ru: '4 ключевых кадра лупа' },
      { en: 'Export and fix pop on frame 1', ru: 'Экспорт и убери рывок на кадре 1' },
      [6, 20, 6],
    ),
  },
  {
    id: 11026,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Walk Contacts Only (4 Poses)', ru: 'Ходьба: только контакты (4 позы)' },
    description: {
      en: 'Four walk contact poses — no in-betweens. Label passing and contact.',
      ru: '4 контактные позы шага — без промежуточных. Подпиши passing и contact.',
    },
    xp: 68,
    estimatedTime: 28,
    min_level: 5,
    tags: ['walk', 'cycle', 'contact'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'walk-contacts',
      { en: '2 contact poses — left/right foot', ru: '2 contact — левая/правая стопа' },
      { en: '4 contacts full cycle', ru: '4 контакта полного цикла' },
      { en: 'Hip height chart on 4 poses', ru: 'График высоты таза на 4 позах' },
      [5, 18, 5],
    ),
  },
  {
    id: 11027,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'howardwimshurst',
    source: 'Howard Wimshurst (YouTube)',
    title: { en: 'Smear Frame Study (3 Frames)', ru: 'Smear: 3 кадра' },
    description: {
      en: 'Fast swing: 3 frames with one smear frame. Readable silhouette on all.',
      ru: 'Быстрый взмах: 3 кадра, один smear. Читаемый силуэт на всех.',
    },
    xp: 95,
    estimatedTime: 38,
    min_level: 9,
    tags: ['smear', 'spacing', 'speed'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'smear-3',
      { en: 'Start and end key silhouettes', ru: 'Силуэты начала и конца' },
      { en: 'Middle smear frame', ru: 'Средний smear-кадр' },
      { en: 'Onion skin check motion path', ru: 'Проверка траектории onion skin' },
      [6, 24, 8],
    ),
  },
  {
    id: 11028,
    category: 'animation',
    difficulty: 'novice',
    inspiredBy: 'howardwimshurst',
    source: 'Howard Wimshurst (YouTube)',
    title: { en: 'Pendulum Slow In/Out', ru: 'Маятник: slow in/out' },
    description: {
      en: '6-frame pendulum swing. Spacing dense at ends, sparse in middle.',
      ru: 'Маятник из 6 кадров. Плотный spacing на концах, редкий в середине.',
    },
    xp: 50,
    estimatedTime: 18,
    min_level: 1,
    tags: ['spacing', 'ease', 'timing'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 0,
    microChallenges: mc(
      'pendulum-ease',
      { en: '2 extreme pendulum keys', ru: '2 крайних ключа маятника' },
      { en: '6 frames with spacing dots', ru: '6 кадров с точками spacing' },
      { en: 'Flip and note where it feels floaty', ru: 'Флипбук — где «плывёт»' },
      [4, 10, 4],
    ),
  },
  {
    id: 11029,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Overlapping Scarf on Walk', ru: 'Overlapping: шарф в шаге' },
    description: {
      en: 'Walk cycle keys + scarf overlap delayed 2 frames. 8 keys minimum.',
      ru: 'Ключи шага + шарф с overlap на 2 кадра позже. Минимум 8 ключей.',
    },
    xp: 88,
    estimatedTime: 40,
    min_level: 6,
    tags: ['overlap', 'follow_through', 'walk'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 14,
    microChallenges: mc(
      'scarf-overlap',
      { en: 'Body walk keys only (4)', ru: '4 ключа тела — шаг' },
      { en: 'Scarf keys offset by 2', ru: 'Ключи шарфа со сдвигом 2' },
      { en: 'Test loop — fix body/scarf pop', ru: 'Тест лупа — убери рывок' },
      [8, 24, 8],
    ),
  },
  {
    id: 11030,
    category: 'animation',
    difficulty: 'novice',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Follow-Through Tail (6 Frames)', ru: 'Follow-through: хвост, 6 кадров' },
    description: {
      en: 'Character jump or turn — tail follows 6 frames after body stops.',
      ru: 'Прыжок или поворот — хвост догоняет 6 кадров после остановки тела.',
    },
    xp: 55,
    estimatedTime: 22,
    min_level: 2,
    tags: ['follow_through', 'overlap'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'tail-follow',
      { en: 'Body keys — start and stop', ru: 'Ключи тела — старт и стоп' },
      { en: '6 tail follow frames', ru: '6 кадров хвоста' },
      { en: 'Drag on last 2 tail frames', ru: 'Drag на последних 2 кадрах хвоста' },
      [4, 14, 4],
    ),
  },
  {
    id: 11031,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Squash & Stretch Prop', ru: 'Squash & stretch на реквизите' },
    description: {
      en: 'Rubber ball or bag hit ground — squash on contact, stretch in air. 6 keys.',
      ru: 'Мяч или мешок — squash на контакте, stretch в воздухе. 6 ключей.',
    },
    xp: 72,
    estimatedTime: 30,
    min_level: 4,
    tags: ['squash', 'stretch', 'weight'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'squash-prop',
      { en: '2 stretch keys in air', ru: '2 stretch в воздухе' },
      { en: 'Squash contact + recovery', ru: 'Squash на контакте + восстановление' },
      { en: 'Volume constant check — same mass', ru: 'Проверка объёма — масса постоянна' },
      [5, 18, 7],
    ),
  },
  {
    id: 11032,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Secondary Action: Hair on Jump', ru: 'Secondary action: волосы в прыжке' },
    description: {
      en: 'Jump cycle with hair secondary motion — body keys + hair delayed 3 frames.',
      ru: 'Прыжок с вторичным движением волос — тело + волосы с задержкой 3 кадра.',
    },
    xp: 105,
    estimatedTime: 48,
    min_level: 10,
    tags: ['secondary', 'overlap', 'hair'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 21,
    microChallenges: mc(
      'hair-secondary',
      { en: 'Body jump keys (5)', ru: '5 ключей прыжка тела' },
      { en: 'Hair keys offset', ru: 'Ключи волос со сдвигом' },
      { en: 'Polish 1 hold on apex', ru: '1 hold на вершине' },
      [8, 30, 10],
    ),
  },
  {
    id: 11033,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'tonikopantoja',
    source: 'Toniko Pantoja (YouTube)',
    title: { en: 'Solid Drawing: 3 Turn Keys', ru: 'Solid drawing: 3 поворота' },
    description: {
      en: 'Same character — 3 rotation keys with consistent volume and proportions.',
      ru: 'Один персонаж — 3 ключа поворота с постоянным объёмом и пропорциями.',
    },
    xp: 98,
    estimatedTime: 42,
    min_level: 9,
    tags: ['solid_drawing', 'consistency', 'character'],
    medium: 'both',
    is_repeatable: false,
    review_after_days: 21,
    microChallenges: mc(
      'solid-turn-3',
      { en: 'Model sheet front reference', ru: 'Референс фронт с model sheet' },
      { en: '3/4 and profile keys', ru: 'Ключи 3/4 и профиль' },
      { en: 'Overlay check proportions', ru: 'Наложение — проверка пропорций' },
      [8, 28, 6],
    ),
  },
  {
    id: 11034,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'pikat',
    source: 'pikat (YouTube)',
    title: { en: 'In-Between Discipline: 5 Pairs', ru: 'Дисциплина in-between: 5 пар' },
    description: {
      en: '5 key pairs with one in-between each — focus on arcs and spacing, not detail.',
      ru: '5 пар ключей с одним in-between — дуги и spacing, не детали.',
    },
    xp: 80,
    estimatedTime: 35,
    min_level: 5,
    tags: ['spacing', 'inbetweens', 'practice'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'inbetween-5',
      { en: '2 pairs — plan spacing dots first', ru: '2 пары — сначала точки spacing' },
      { en: '5 in-betweens complete', ru: '5 in-between готовы' },
      { en: 'Flip worst pair twice', ru: 'Дважды флип худшей пары' },
      [6, 24, 5],
    ),
  },
  {
    id: 11035,
    category: 'animation',
    difficulty: 'intermediate',
    inspiredBy: 'rjanimationstoo',
    source: 'RJ Animations Too (YouTube)',
    title: { en: 'Lip Sync Mouth Shapes (4)', ru: 'Lip sync: 4 формы рта' },
    description: {
      en: 'Draw 4 mouth shapes — A, E, O, closed — same head angle. Label phoneme.',
      ru: '4 формы рта — A, E, O, закрытый — один ракурс головы. Подпиши фонему.',
    },
    xp: 65,
    estimatedTime: 28,
    min_level: 5,
    tags: ['lip_sync', 'face', 'acting'],
    medium: 'digital',
    is_repeatable: true,
    review_after_days: 14,
    microChallenges: mc(
      'lipsync-4',
      { en: 'Neutral mouth + line of face', ru: 'Нейтральный рот + линия лица' },
      { en: '4 mouth shapes', ru: '4 формы рта' },
      { en: '2-frame blink between shapes test', ru: 'Тест 2 кадра между формами' },
      [5, 18, 5],
    ),
  },
  {
    id: 11036,
    category: 'animation',
    difficulty: 'novice',
    inspiredBy: 'alanbeckertutorials',
    source: 'Alan Becker Tutorials (YouTube)',
    title: { en: 'Stick Figure Run (6 Keys)', ru: 'Бег палочки: 6 ключей' },
    description: {
      en: '6-key run cycle for stick figure. Contacts and passing labeled.',
      ru: 'Цикл бега палочки — 6 ключей. Contact и passing подписаны.',
    },
    xp: 54,
    estimatedTime: 22,
    min_level: 2,
    tags: ['run', 'cycle', 'basics'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'stick-run',
      { en: '2 contact poses', ru: '2 contact-позы' },
      { en: '6-key run', ru: '6 ключей бега' },
      { en: 'GIF loop export', ru: 'Экспорт GIF-лупа' },
      [4, 14, 4],
    ),
  },
  {
    id: 11037,
    category: 'animation',
    difficulty: 'advanced',
    inspiredBy: 'howardwimshurst',
    source: 'Howard Wimshurst (YouTube)',
    title: { en: 'Fast Motion Blur Strip', ru: 'Полоса быстрого движения' },
    description: {
      en: 'One fast action — 5 frames with blur/smear strip. Timing chart required.',
      ru: 'Быстрое действие — 5 кадров с blur/smear. Нужен график тайминга.',
    },
    xp: 100,
    estimatedTime: 40,
    min_level: 11,
    tags: ['speed', 'smear', 'timing'],
    medium: 'digital',
    is_repeatable: false,
    review_after_days: 21,
    prerequisites: [11027],
    microChallenges: mc(
      'fast-blur',
      { en: 'Timing chart for 5 frames', ru: 'График тайминга на 5 кадров' },
      { en: 'Keys + smear strip', ru: 'Ключи + полоса smear' },
      { en: 'Playblast or GIF test', ru: 'Playblast или GIF-тест' },
      [8, 26, 6],
    ),
  },
  {
    id: 11038,
    category: 'animation',
    difficulty: 'novice',
    inspiredBy: 'dongchang',
    source: 'Dong Chang (YouTube)',
    title: { en: 'Weight Drop Chart + 6 Frames', ru: 'Падение с весом: график + 6 кадров' },
    description: {
      en: 'Object falls with acceleration — timing chart + 6 frames. Note ease-in to ground.',
      ru: 'Падение с ускорением — график + 6 кадров. Ease-in к земле.',
    },
    xp: 56,
    estimatedTime: 24,
    min_level: 2,
    tags: ['weight', 'gravity', 'charts'],
    medium: 'both',
    is_repeatable: true,
    review_after_days: 7,
    microChallenges: mc(
      'weight-drop',
      { en: 'Chart spacing accelerating down', ru: 'График — сжатие spacing вниз' },
      { en: '6 drop frames', ru: '6 кадров падения' },
      { en: 'Small squash on last frame', ru: 'Лёгкий squash на последнем' },
      [5, 15, 4],
    ),
  },
]
